language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - python setup.py install
  - pip install coveralls --use-mirrors
script:
  - nosetests --with-coverage --cover-package=mangopi
after_success:
  - coveralls
